from django.urls import path
from .views import (
    ConsentSignatureView,
    ConsentSignatureDetailView,
    ProfileView,
    QuestionnaireSubmissionView,
    QuestionnaireSubmissionDetailView,
    SignatureCheckLogView,
    RecordingClipView,
    RecordingSessionView,
    RecordingSessionDetailView,
    RespondentManagementView,
    AdminSubjectRecordsView,
    AdminRespondentPasswordResetView,
    AdminRespondentMarkCheckedView,
    AdminRespondentMarkDoneView,
    AdminSubjectQuestionnaireDetailView,
    AdminSubjectRecordingSessionDetailView,
    LoginView,
)

urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('signatures/', ConsentSignatureView.as_view(), name='consent-signatures'),
    path('signatures/<uuid:signature_id>/', ConsentSignatureDetailView.as_view(), name='consent-signatures-detail'),
    path('signatures/<uuid:signature_id>/checks/', SignatureCheckLogView.as_view(), name='signature-checks'),
    path('questionnaires/', QuestionnaireSubmissionView.as_view(), name='questionnaire-submissions'),
    path('questionnaires/<uuid:submission_id>/', QuestionnaireSubmissionDetailView.as_view(), name='questionnaire-submissions-detail'),
    path('recordings/', RecordingClipView.as_view(), name='recording-clips'),
    path('recording-sessions/', RecordingSessionView.as_view(), name='recording-sessions'),
    path('recording-sessions/<uuid:session_id>/', RecordingSessionDetailView.as_view(), name='recording-sessions-detail'),
    path('admin/respondents/', RespondentManagementView.as_view(), name='admin-respondents'),
    path('admin/respondents/<int:user_id>/records/', AdminSubjectRecordsView.as_view(), name='admin-subject-records'),
    path(
        'admin/respondents/<int:user_id>/questionnaires/<uuid:submission_id>/',
        AdminSubjectQuestionnaireDetailView.as_view(),
        name='admin-subject-questionnaire-detail',
    ),
    path(
        'admin/respondents/<int:user_id>/recording-sessions/<uuid:session_id>/',
        AdminSubjectRecordingSessionDetailView.as_view(),
        name='admin-subject-recording-session-detail',
    ),
    path('admin/respondents/<int:user_id>/reset-password/', AdminRespondentPasswordResetView.as_view(), name='admin-respondent-reset-password'),
    path('admin/respondents/<int:user_id>/mark-checked/', AdminRespondentMarkCheckedView.as_view(), name='admin-respondent-mark-checked'),
    path('admin/respondents/<int:user_id>/mark-done/', AdminRespondentMarkDoneView.as_view(), name='admin-respondent-mark-done'),
    path('auth/login/', LoginView.as_view(), name='login'),
]
